[ui]
editor = "nvim"

[aliases]
xl = ["log", "--no-pager"]
up = ["edit"]
sync = ["rebase", "-b", "@", "-d", "trunk()"]
pdiff = ["diff", "-r", "@-"]
mdiff = ["diff", "--from", "master"]
promote = ["bookmark", "move", "--from", "bookmarks() & ..@ & (~(..bookmarks()-))"]

[revset-aliases]
tip = 'heads(@::)'

[fix.tools.pre-commit]
command = ["bash", "-c", "cat; pre-commit run --files $path  > /dev/null 2> /dev/null"]
patterns = ["glob:'**/*'"]
